config/routes.rb
Rails.application.routes.draw do
  root "profiles#index"
  resources :profiles
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#new'
  get '/signup' => 'users#new'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :profiles
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    unless current_user
      flash[:errors] = "You need to sign in or sign up before continuing"
      redirect_to new_session_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate, only: :show

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(email: params[:email]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Signed in successfully"
      redirect_to root_path
    else
      flash[:errors] = "Invalid username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Signed out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'User successfully created.'
      redirect_to root_path
    else
      flash[:errors] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_top_bar.html.erb
<% if current_user %>
  Signed in as <%= current_user.username %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Profilez" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/top_bar' %>

    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>

    <div class="row">
      <div class="small-12 columns centered">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/profiles/index.html.erb
<h2>Profilez Index Page!</h2>

<% @profiles.each do |profile| %>
  <li><%= profile.user.username %>: <%= link_to profile.one_liner, profile_path(profile) %></li>
<% end %>

app/views/profiles/show.html.erb
<h2><%= @profile.user.username %>'s Show Page!</h2>

<h3><%= @profile.one_liner %></h3>

My favorite color is: <%= @profile.favorite_color %>

<h3>About Me</h3>

<%= @profile.about_me %><p>

<%= link_to "Back to Profilez Index", profiles_path %>

app/views/users/new.html.erb
<div class="row">
  <div class="small-6 small-centered columns">
    <h1>Signup!</h1>
    <%= form_for @user do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit %>
    <% end %>
  </div>
</div>